### ISSUE TITLE
Response 503 - Need Read Permission

### ISSUE THREAD

**Issue by nkrabben** [mementoweb/mediawiki-memento-headers#1]
I tried installing the extension on several of our wikis. On some, it work perfectly, but on those with at least some content visible only to logged in users, I get this error:
`503 
 {u'info': u'You need read permission to use this module', u'code': u'readapidenied'}`

Here's an example:
http://timetravel.mementoweb.org/mediawiki/timegate/http://metaarchive.org/metawiki/index.php/MetaWiki_Home

The only other extension installed is Google Analytics.

**Comment by shawnmjones** [comment]
I am looking into this.  I'll let you know what I discover.  Thank you for using the extension!

**Comment by shawnmjones** [comment]
Do you have $wgEnableAPI = false in your LocalSettings.php?

I believe the default is true, but you can try $wgEnableAPI = true; and see if it works afterwards.

**Comment by nkrabben** [comment]
That wasn't in our LocalSettings.php, so I added it. I still get the same error.

**Comment by nkrabben** [comment]
The way content visibility has been controlled is setting
`$wgGroupPermissions['*'    ]['read']            = false;`
and then creating a whitelist
`$wgWhitelistRead = array(...)`

I wouldn't be surprised if that first command is causing the readapidenied.

**Comment by shawnmjones** [comment]
I have come to that conclusion as well.  We have a local private wiki that has some restricted pages and I have duplicated the issue using that wiki.

**Comment by shawnmjones** [comment]
I've figured out what the problem is, and it cannot be fixed with the headers extension alone.

All of our testing on the Headers extension centered on wikis that had no restricted content.

The problem for a wiki with authentication AND some restricted pages:
1. A user uses a browser (like Chrome) running a Memento extension to visit a restricted MediaWiki
2. The user logs into that MediaWiki site, the browser sends back a cookie containing session information
3. With every request, the cookies containing their session key are sent from client to server
4. When the proxy at http://timetravel.mementoweb.org/ attempts to contact the API, it is unaware of the session key, so it cannot log in to the MediaWiki instance and the MediaWiki API's response is this JSON 503 error

On a wiki without restricted content, this issue doesn't exist because the API can access every page.

According to: http://www.mediawiki.org/wiki/API:FAQ#do_I_get_the_readapidenied_error.3F
"It's not currently possible to query the contents of whitelisted pages without logging in, even though they're available in the regular user interface."

The full extension (see https://www.mediawiki.org/wiki/Extension:Memento) does not have this problem because there is no intermediary Memento proxy, therefore all communications are directly between the Memento client (Chrome with Memento extension) and the MediaWiki server.

Thanks for finding this.  We suggest using the full extension to provide Memento capability for your wiki.  It has been tested in more environments and has undergone code reviews by several developers on the MediaWiki team.

**Comment by nkrabben** [comment]
Thanks for documenting this. I'll start testing the full extension.
